######################################################################
# Automatically generated by qmake (3.0) Sat Apr 21 14:36:09 2018
######################################################################

TEMPLATE = app
TARGET = p20
INCLUDEPATH += .

# Input
HEADERS += line.h pos.h window.h board.h colourpicker.h serial.h
SOURCES += line.cpp pos.cpp window.cpp main.cpp board.cpp colourpicker.cpp serial.cpp
QT += core gui widgets
